### ISSUE TITLE
Css Only Framework?

### ISSUE THREAD

**Issue by whatisgravity** [nesbtesh/Bootless#1]
I'm looking for interesting css only frameworks, is this planned to be CSS only or CSS/JS minimal framework?

**Comment by nesbtesh** [comment]
Hey thanks, this will always be a CSS only framework

**Comment by whatisgravity** [comment]
Awesome, I look forward to seeing this project grow. As it develops I may be able to help, right now I'm contributing to Surface a CSS only material framework. 

Also, great name.

**Comment by nesbtesh** [comment]
Let me know what you think of the docs http://nesbtesh.github.io/Nessim-Btesh/bootless/

**Comment by whatisgravity** [comment]
Good, it appears the placeholder text color is not consistent across the forms. Otherwise looks very good.
